name: Deploy APIM Infra

on:
  workflow_dispatch:
  push:
    branches:
      - v2
    paths:
      - 'bicep/deploy.bicep'
      - 'bicep/onpremise.bicep'
      - '.github/workflows/deploy-apim.yml'
env:
  APIM_RESOURCE_GROUP_NAME: api-demo-rg
  ON_PREM_RESOURCE_GROUP_NAME: onprem-demo-rg
  LOCATION: eastus

jobs:
  deploy_apim_resources:
    runs-on: ubuntu-latest 
    
    # Map outputs of the job
    outputs:
      apimSubnetCIDR: ${{ steps.deployapim.outputs.apimSubnetCIDR }}

    steps:
      - uses: actions/checkout@v2

      # Login to Azure
      - name: Azure Login
        uses: Azure/login@v1.1
        with:          
          creds: ${{ secrets.SP_AZURE_CREDENTIALS }}          
          enable-AzPSSession: false
      
      # Compile bicep files
      - name: Bicep Build
        uses: aliencube/bicep-build-actions@v0.1
        with:
          files: bicep/deploy.bicep
                
      # Create resource group
      - name: Create Resource Group
        run: |
         az group create -n ${{ env.APIM_RESOURCE_GROUP_NAME }} -l ${{ env.LOCATION }}

      # Replace parameters with secrets
      - name: Replace tokens
        uses: cschleiden/replace-tokens@v1.0
        with:        
          tokenPrefix: __        
          tokenSuffix: __        
          files: '["deploy.parameters.json"]'
        env:
          publisherName: ${{ secrets.PUBLISHER_NAME }}
          publisherEmail: ${{ secrets.PUBLISHER_EMAIL }}
          adminUsernameSql: ${{ secrets.ADMIN_USERNAME_SQL }}
          adminPasswordSql: ${{ secrets.ADMIN_PASSWORD_SQL }}
          hostname: ${{ secrets.HOSTNAME }}
          adminUsername: ${{ secrets.ADMIN_USERNAME }}
          adminPassword: ${{ secrets.ADMIN_PASSWORD }}
                              
      - name: Deploy APIM Resources
        id: deployapim
        uses: Azure/arm-deploy@v1.0.1
        with:        
          scope: resourcegroup          
          subscriptionId: ${{ secrets.SUBSCRIPTION_ID }}          
          region: ${{ env.LOCATION }}        
          resourceGroupName: ${{ env.APIM_RESOURCE_GROUP_NAME }}        
          template: bicep/deploy.json   
          parameters: deploy.parameters.json
          deploymentMode: Incremental     

  deploy_onpremise_resources:
    runs-on: ubuntu-latest
    needs: deploy_apim_resources

    steps:
      - uses: actions/checkout@v2

      # Login to Azure
      - name: Azure Login
        uses: Azure/login@v1.1
        with:          
          creds: ${{ secrets.SP_AZURE_CREDENTIALS }}          
          enable-AzPSSession: false

      # Compile bicep files
      - name: Bicep Build
        uses: aliencube/bicep-build-actions@v0.1
        with:
          files: bicep/onpremise.bicep

      # Create resource group
      - name: Create Resource Group
        run: |
         az group create -n ${{ env.ON_PREM_RESOURCE_GROUP_NAME }} -l ${{ env.LOCATION }}  

      # Replace parameters
      - name: Replace tokens
        uses: cschleiden/replace-tokens@v1.0
        with:        
          tokenPrefix: __        
          tokenSuffix: __        
          files: '["onpremise.parameters.json"]'
        env:
          apimSubnetCIDR: ${{ needs.deploy_apim_resources.outputs.apimSubnetCIDR }}
          adminUsername: ${{ secrets.ADMIN_USERNAME }}
          adminPassword: ${{ secrets.ADMIN_PASSWORD }}          

      - name: Deploy On Premise Resources
        id: deployapim
        uses: Azure/arm-deploy@v1.0.1
        with:        
          scope: resourcegroup          
          subscriptionId: ${{ secrets.SUBSCRIPTION_ID }}          
          region: ${{ env.LOCATION }}        
          resourceGroupName: ${{ env.ON_PREM_RESOURCE_GROUP_NAME }}        
          template: bicep/onpremise.json   
          parameters: onpremise.parameters.json
          deploymentMode: Incremental              